Repository elastic/ecctl, pull requests merged in 2019-12, with the labels that each got.

#70 docs: Remove tap pin step from brew instructions
  docs/ecctl-getting-started.asciidoc
Labels: area:tooling, documentation, loe:small

#71 cmd: Migrate kibana create to deployments API
  cmd/deployment/elasticsearch/create.go
  cmd/deployment/kibana/command.go
  cmd/deployment/kibana/create.go
  cmd/deployment/kibana/create_help.go
  cmd/deployment/kibana/enable.go
  docs/ecctl_deployment_kibana.md
  docs/ecctl_deployment_kibana_create.md
  docs/ecctl_deployment_kibana_enable.md
  pkg/deployment/depresource/deployment_info.go
  pkg/deployment/depresource/kibana.go
  pkg/deployment/depresource/kibana_test.go
  pkg/deployment/depresource/track.go
  pkg/deployment/depresource/track_test.go
  pkg/deployment/kibana/create.go
  pkg/deployment/kibana/create_test.go
  pkg/deployment/kibana/enable.go
  pkg/deployment/kibana/enable_test.go
  pkg/deployment/kibana/params.go
Labels: area:tooling, enhancement, loe:large

#82 Support vacate override failsafe
  cmd/platform/allocator/vacate.go
  docs/ecctl_platform_allocator_vacate.md
  pkg/platform/allocator/vacate.go
  pkg/platform/allocator/vacate_params.go
  pkg/platform/allocator/vacate_test.go
Labels: area:tooling

#80 cmd: Add --track flag to deployment commands
  cmd/deployment/create.go
  cmd/deployment/shutdown.go
  cmd/deployment/update.go
  docs/ecctl_deployment_create.md
  docs/ecctl_deployment_shutdown.md
  docs/ecctl_deployment_update.md
Labels: area:tooling, enhancement, loe:small

#93 cmd: Remove elasticsearch create
  cmd/deployment/elasticsearch/create.go
  cmd/deployment/elasticsearch/create_help.go
  docs/ecctl_deployment_elasticsearch.md
  docs/ecctl_deployment_elasticsearch_create.md
Labels: area:tooling, loe:small

#94 Version: Change to v1.0.0-beta1
  Makefile
Labels: area:tooling

#96 cmd: update resource params to use common struct
  cmd/deployment/plan/cancel.go
  cmd/deployment/resource/start-maintenance.go
  cmd/deployment/resource/start.go
  cmd/deployment/resource/stop-maintenance.go
  cmd/deployment/resource/stop.go
  go.mod
  pkg/deployment/depresource/cancel_plan.go
  pkg/deployment/depresource/cancel_plan_test.go
  pkg/deployment/depresource/start.go
  pkg/deployment/depresource/start_maintenance.go
  pkg/deployment/depresource/start_maintenance_test.go
  pkg/deployment/depresource/start_test.go
  pkg/deployment/depresource/stop.go
  pkg/deployment/depresource/stop_maintenance.go
  pkg/deployment/depresource/stop_maintenance_test.go
  pkg/deployment/depresource/stop_test.go
Labels: area:tooling, enhancement, loe:medium

#92 cmd: Add ref-id auto-discovery to resource upgrade
  cmd/deployment/resource/upgrade.go
  pkg/deployment/depresource/upgrade_stateless.go
  pkg/deployment/depresource/upgrade_stateless_test.go
Labels: area:tooling, bug, loe:small

#98 dep: update cloud-sdk-go to v1.0.0-bc9
  go.mod
  go.sum
Labels: area:tooling, dependencies, loe:small

#100 Add timeout values to ecctl.Config
  cmd/root.go
  pkg/ecctl/app.go
  pkg/ecctl/config.go
Labels: area:tooling, loe:small

#102 Update ecctl-getting-started.asciidoc
  docs/ecctl-getting-started.asciidoc
Labels: area:tooling, documentation

#104 bug: fix resource delete refid discovery and require confirmation
  cmd/deployment/resource/delete.go
  pkg/deployment/depresource/delete_stateless.go
Labels: area:tooling, bug, loe:medium

#106 user: Fix key show command
  cmd/user/key/show.go
  pkg/user/auth/admin/getkey.go
Labels: area:tooling, bug, loe:small

#101 Add auto completion intruction to docs
  .goreleaser.yml
  docs/ecctl-getting-started.asciidoc
Labels: area:tooling, documentation, loe:small

#103 cmd: Remove newer version check on ecctl version
  Makefile
  NOTICE
  cmd/version.go
  go.mod
  go.sum
Labels: area:tooling, loe:small

#109 cmd: Add default region to APM and Kibana create
  cmd/deployment/apm/create.go
  cmd/deployment/kibana/create.go
Labels: area:tooling, bug, loe:small

#110 elasticsearch: Fix broken diagnostics command
  cmd/deployment/elasticsearch/diagnose.go
  docs/ecctl_deployment_elasticsearch_diagnose.md
Labels: area:tooling, bug, loe:small

#105 stack: Skip returning an error on packed __MACOSX
  pkg/platform/stack/stack.go
Labels: area:tooling, bug, loe:small

#108 cmd: fix command wording
  cmd/deployment/apm/create.go
  cmd/deployment/elasticsearch/upgrade.go
  cmd/deployment/kibana/create.go
  docs/ecctl_deployment_apm_create.md
  docs/ecctl_deployment_elasticsearch_upgrade.md
  docs/ecctl_deployment_kibana_create.md
Labels: area:tooling, documentation, loe:small

#112 notes: Generate changelog for v1.0.0-beta1 release
  notes/.gitignore
  notes/v1.0.0-beta1.md
Labels: area:tooling, loe:medium

#113 cmd: Use force flag with instance override
  cmd/deployment/elasticsearch/instances/override.go
Labels: area:tooling, bug, loe:small
