Repository elastic/ecctl, pull requests merged in 2019-11, with the labels that each got.

#23 Beta doc updates
  docs/ecctl-getting-started.asciidoc
  docs/page_header.html
Labels: documentation

#39 init: Skips TLS validation on API calls
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: bug, loe:small

#47 remove plural aliases and update docs
  cmd/platform/allocator/list.go
  cmd/platform/constructor/command.go
  cmd/platform/enrollment-token/command.go
  cmd/platform/platform.go
  cmd/platform/proxy/command.go
  cmd/platform/proxy/filteredgroup/list.go
  cmd/platform/stack/command.go
  docs/ecctl_platform.md
  docs/ecctl_platform_allocators.md
  docs/ecctl_platform_constructors.md
  docs/ecctl_platform_enrollment-tokens.md
  docs/ecctl_platform_proxies.md
  docs/ecctl_platform_proxy.md
  docs/ecctl_platform_proxy_filtered-groups.md
  docs/ecctl_platform_stacks.md
Labels: area:tooling

#48 go.mod: Update cloud-sdk-go to version v1.0.0-bc4
  cmd/deployment/create.go
  docs/ecctl_deployment_create.md
  go.mod
  go.sum
  pkg/deployment/apm/resync_test.go
  pkg/deployment/create_test.go
  pkg/deployment/delete_test.go
  pkg/deployment/elasticsearch/create_test.go
  pkg/deployment/elasticsearch/delete_test.go
  pkg/deployment/elasticsearch/diagnose_test.go
  pkg/deployment/elasticsearch/instances/lifecycle_test.go
  pkg/deployment/elasticsearch/instances/reducer_test.go
  pkg/deployment/elasticsearch/instances/routing_test.go
  pkg/deployment/elasticsearch/list_test.go
  pkg/deployment/elasticsearch/metadata/cluster_metadata_test.go
  pkg/deployment/elasticsearch/monitoring/monitoring_test.go
  pkg/deployment/elasticsearch/plan/read_test.go
  pkg/deployment/elasticsearch/query_test.go
  pkg/deployment/elasticsearch/reallocate_test.go
  pkg/deployment/elasticsearch/restart_test.go
  pkg/deployment/elasticsearch/resync_test.go
  pkg/deployment/elasticsearch/search_test.go
  pkg/deployment/elasticsearch/shutdown_test.go
  pkg/deployment/elasticsearch/upgrade_test.go
  pkg/deployment/kibana/resync_test.go
  pkg/deployment/list_test.go
  pkg/deployment/restore_test.go
  pkg/deployment/search_test.go
  pkg/deployment/shutdown_test.go
  pkg/platform/allocator/allocator_test.go
  pkg/platform/allocator/metadata_test.go
  pkg/platform/allocator/search_test.go
  pkg/platform/info_test.go
  pkg/platform/instanceconfig/instanceconfig_test.go
  pkg/platform/proxy/filteredgroup/filtered_group_test.go
  pkg/platform/proxy/proxy_test.go
  pkg/platform/role/add_blessing_test.go
  pkg/platform/role/create_test.go
  pkg/platform/role/delete_test.go
  pkg/platform/role/list_test.go
  pkg/platform/role/set_blessing_test.go
  pkg/platform/role/show_test.go
  pkg/platform/role/update_test.go
  pkg/platform/snaprepo/repository_test.go
  pkg/platform/stack/stack_test.go
  pkg/user/auth/admin/listkeys_test.go
  pkg/user/auth/listkeys_test.go
  pkg/user/create_test.go
  pkg/user/delete_test.go
  pkg/user/get_test.go
  pkg/user/list_test.go
Labels: enhancement, loe:small

#49 docs: Change the term Kibana Cluster to instance
  cmd/deployment/kibana/command.go
  cmd/deployment/kibana/create.go
  cmd/deployment/kibana/delete.go
  cmd/deployment/kibana/list.go
  cmd/deployment/kibana/reallocate.go
  cmd/deployment/kibana/restart.go
  cmd/deployment/kibana/resync.go
  cmd/deployment/kibana/start.go
  cmd/deployment/kibana/stop.go
  cmd/deployment/kibana/upgrade.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_kibana.md
  docs/ecctl_deployment_kibana_create.md
  docs/ecctl_deployment_kibana_delete.md
  docs/ecctl_deployment_kibana_enable.md
  docs/ecctl_deployment_kibana_list.md
  docs/ecctl_deployment_kibana_plan.md
  docs/ecctl_deployment_kibana_reallocate.md
  docs/ecctl_deployment_kibana_restart.md
  docs/ecctl_deployment_kibana_resync.md
  docs/ecctl_deployment_kibana_show.md
  docs/ecctl_deployment_kibana_start.md
  docs/ecctl_deployment_kibana_stop.md
  docs/ecctl_deployment_kibana_upgrade.md
  pkg/deployment/kibana/create_test.go
  pkg/deployment/kibana/enable.go
  pkg/deployment/kibana/read.go
  pkg/deployment/kibana/reallocate.go
  pkg/deployment/kibana/reallocate_test.go
  pkg/deployment/kibana/restart.go
  pkg/deployment/kibana/resync.go
  pkg/deployment/kibana/resync_test.go
  pkg/platform/allocator/vacate_full_test.go
  pkg/platform/allocator/vacate_responses_test.go
  pkg/platform/allocator/vacate_test.go
Labels: area:tooling, documentation, loe:small

#51 init: Ensure homepath is created
  cmd/init.go
Labels: bug, loe:small

#53 version: Extend output to include ECE API Version
  build/Makefile.build
  cmd/root.go
  cmd/version.go
  go.mod
  go.sum
  main.go
  pkg/ecctl/version.go
  pkg/ecctl/version_test.go
Labels: area:tooling, enhancement, loe:small

#54 init: Remove mentions of ESS in config bootstrap
  docs/ecctl-getting-started.asciidoc
  pkg/ecctl/init.go
Labels: area:tooling, loe:small

#55 deployment: Add update command
  cmd/deployment/create.go
  cmd/deployment/update.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_update.md
  pkg/deployment/create.go
  pkg/deployment/create_test.go
  pkg/deployment/override_settings.go
  pkg/deployment/override_settings_test.go
  pkg/deployment/update.go
  pkg/deployment/update_test.go
Labels: enhancement, loe:medium

#59 http: Add api.DefaultTransport in http.Client
  NOTICE
  cmd/root.go
  go.mod
  go.sum
Labels: area:tooling, bug, loe:small

#57 deployment: Fix show resource type command
  cmd/deployment/show.go
  docs/ecctl_deployment_show.md
  pkg/deployment/get.go
  pkg/deployment/get_resource.go
  pkg/deployment/get_resource_test.go
Labels: area:tooling, bug, loe:large

#64 cmd: Fix init command on unexisting .ecctl folder
  cmd/init.go
Labels: area:tooling, bug, loe:small

#66 Remove ErrCatchTransport from default http client
  cmd/root.go
  go.mod
  go.sum
  pkg/ecctl/init.go
Labels: area:tooling, bug, loe:small
