Repository elastic/ecctl, pull requests merged in 2020-01, with the labels that each got.

#115 cmd: Fix deployment create typo
  cmd/deployment/create.go
  docs/ecctl_deployment_create.md
Labels: area:tooling, bug, loe:small

#118 deployments: Change refID defaults to use 'main-' prefix
  cmd/deployment/apm/create.go
  cmd/deployment/kibana/create.go
  docs/ecctl_deployment_apm_create.md
  docs/ecctl_deployment_kibana_create.md
  pkg/deployment/depresource/apm.go
  pkg/deployment/depresource/apm_test.go
  pkg/deployment/depresource/elasticsearch.go
  pkg/deployment/depresource/kibana.go
  pkg/deployment/depresource/kibana_test.go
Labels: area:tooling, enhancement, loe:small

#117 release: v1.0.0-beta1 release fixes
  .goreleaser.yml
  build/Dockerfile.goreleaser
  build/Makefile.build
  notes/v1.0.0-beta1.md
  scripts/generate-changelog.sh
  scripts/goreleaser
Labels: area:tooling, bug, loe:medium

#119 cmd: Add --skip-tracking flag to allocator vacate
  cmd/platform/allocator/vacate.go
  docs/ecctl_platform_allocator_vacate.md
  pkg/platform/allocator/vacate.go
  pkg/platform/allocator/vacate_params.go
  pkg/platform/allocator/vacate_test.go
Labels: area:tooling, enhancement, loe:small

#120 cmd: Add allocator show allocated instance details
  pkg/formatter/templates/bindata.go
  pkg/formatter/templates/text/allocator/show.gotmpl
  pkg/formatter/templates/text/allocator/showmetadata.gotmpl
Labels: area:tooling, breaking-change, enhancement, loe:small

#122 deployment: Add --type flag autocompletion
  cmd/deployment/plan/cancel.go
  cmd/deployment/resource/delete.go
  cmd/deployment/resource/restore.go
  cmd/deployment/resource/shutdown.go
  cmd/deployment/resource/start-maintenance.go
  cmd/deployment/resource/start.go
  cmd/deployment/resource/stop-maintenance.go
  cmd/deployment/resource/stop.go
  cmd/deployment/resource/upgrade.go
  cmd/deployment/show.go
  cmd/root.go
  cmd/util/flag.go
  cmd/util/flag_test.go
  docs/ecctl_deployment_plan_cancel.md
  docs/ecctl_deployment_resource_delete.md
  docs/ecctl_deployment_resource_restore.md
  docs/ecctl_deployment_resource_shutdown.md
  docs/ecctl_deployment_resource_start-maintenance.md
  docs/ecctl_deployment_resource_start.md
  docs/ecctl_deployment_resource_stop-maintenance.md
  docs/ecctl_deployment_resource_stop.md
  docs/ecctl_deployment_resource_upgrade.md
  docs/ecctl_deployment_show.md
  go.mod
Labels: area:tooling, enhancement, loe:medium

#126 Update usage example for beta1
  docs/ecctl-getting-started.asciidoc
Labels: documentation

#123 Add beta1 release notes
  docs/ecctl-release-notes.asciidoc
  docs/index.asciidoc
Labels: area:tooling, documentation

#124 cmd: add --all flag to kibana resync command
  cmd/deployment/kibana/resync.go
  docs/ecctl_deployment_kibana.md
  docs/ecctl_deployment_kibana_resync.md
  pkg/deployment/kibana/resync.go
  pkg/deployment/kibana/resync_test.go
Labels: area:tooling, enhancement, loe:medium

#125 cmd: add --all flag to apm resync command
  cmd/deployment/apm/resync.go
  docs/ecctl_deployment_apm.md
  docs/ecctl_deployment_apm_resync.md
  pkg/deployment/apm/resync.go
  pkg/deployment/apm/resync_test.go
Labels: area:tooling, enhancement, loe:medium

#130 cmd: Add deployment resync and --all flag
  cmd/deployment/resync.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_resync.md
  pkg/deployment/resync.go
  pkg/deployment/resync_test.go
Labels: area:tooling, enhancement, loe:medium

#134 Update the v1.0.0-beta1 release notes with information from Marc's changelog
  docs/ecctl-release-notes.asciidoc
Labels: documentation

#136 platform/repository: Fix list format
  cmd/platform/repository/command.go
  pkg/formatter/templates/bindata.go
  pkg/formatter/templates/text/platform/repositorylist.gotmpl
Labels: area:tooling, bug, loe:small

#135 util: Change default tracking poll interval
  pkg/util/track.go
Labels: area:tooling, enhancement, loe:small

#137 release: Automate release in GitHub action
  .github/workflows/release.yml
  developer_docs/RELEASE.md
  scripts/goreleaser
  scripts/goreleaser-post-actions.sh
  scripts/update-brew-tap.sh
Labels: area:tooling, enhancement, loe:medium

#139 misc: adds a `go mod tidy` command to the goreleaser.yml
  .goreleaser.yml
Labels: area:tooling, bug, loe:small

#141 Fix goreleaser gh actions workflow
  .github/workflows/release.yml
Labels: area:tooling, bug, loe:small

#144 Point ot the latest cloud-sdk-go version
  go.mod
  go.sum
Labels: area:tooling

#146 deployment: Fix empty region bug when specified
  cmd/deployment/apm/create.go
  cmd/deployment/create.go
  cmd/deployment/kibana/create.go
  cmd/deployment/update.go
Labels: area:tooling, bug, loe:small

#147 go.mod: Update cloud-sdk-go to v1.0.0-bc12
  go.mod
  go.sum
Labels: area:tooling, bug, loe:small

#151 Change allocator vacate default polling settings
  cmd/platform/allocator/vacate.go
  cmd/util/flag.go
  cmd/util/flag_test.go
  docs/ecctl_platform_allocator_vacate.md
  pkg/platform/allocator/vacate.go
  pkg/platform/allocator/vacate_test.go
Labels: area:tooling, enhancement, loe:small

#152 release: Remove v prefix from binaries and path
  .goreleaser.yml
  scripts/goreleaser
  scripts/goreleaser-post-actions.sh
Labels: area:tooling, bug, loe:small
