Repository elastic/ecctl, pull requests merged in 2020-05, with the labels that each got.

#274 docs: Update release documentation and release GH issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/GENERIC_QUESTION.md
  .github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md
  developer_docs/RELEASE.md
  developer_docs/docs-rebuild.png
Labels: area:delivery, documentation

#279 misc: update issue template labels
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/GENERIC_QUESTION.md
  .github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md
Labels: Team:Delivery

#280 cmd: fix deployment shutdown command
  cmd/deployment/shutdown.go
  docs/ecctl_deployment_shutdown.adoc
  docs/ecctl_deployment_shutdown.md
  pkg/deployment/shutdown.go
Labels: Team:Delivery, breaking-change, bug

#282 omitting ece-only support statement from readme
  README.md
Labels: Team:Delivery, documentation

#278 cmd: rephrase deployment create flag, error and help text
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
Labels: Team:Delivery

#271 docs: Update deployment create help wording
  cmd/deployment/create_help.go
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
Labels: Team:Delivery, blocked, documentation

#273 release: Update version, create release notes and generate changelog
  Makefile
  docs/ecctl-release-notes.asciidoc
  docs/release_notes/v1.0.0-beta3.adoc
  notes/v1.0.0-beta3.md
  scripts/changelog.tpl.adoc
  scripts/changelog.tpl.md
Labels: Team:Delivery

#287 release: Fix git config and changelog format
  .github/workflows/release.yml
  notes/v1.0.0-beta3.md
  scripts/changelog.tpl.md
  scripts/update-brew-tap.sh
Labels: Team:Delivery

#294 mod: Update vendor to 60b0cbb commit
  cmd/deployment/update.go
  go.mod
  go.sum
Labels: bug
