Repository elastic/ecctl, pull requests merged in 2020-07, with the labels that each got.

#336 cmd: fix testutil.newConfig ignored region
  cmd/util/testutils/testutils.go
  cmd/util/testutils/testutils_test.go
Labels: Team:Delivery

#332 deployment-template: Adds a new --template-format flag to command
  cmd/platform/deployment-template/command.go
  cmd/platform/deployment-template/list.go
  cmd/platform/deployment-template/list_test.go
  cmd/platform/deployment-template/pull.go
  cmd/platform/deployment-template/show.go
  cmd/platform/deployment-template/show_test.go
  docs/ecctl_platform_deployment-template_list.adoc
  docs/ecctl_platform_deployment-template_list.md
  docs/ecctl_platform_deployment-template_pull.adoc
  docs/ecctl_platform_deployment-template_pull.md
  docs/ecctl_platform_deployment-template_show.adoc
  docs/ecctl_platform_deployment-template_show.md
  go.mod
  go.sum
Labels: enhancement

#337 cmd: Remove sdkcmdutil.FileOrStdin use
  cmd/deployment/create.go
  cmd/platform/deployment-template/create.go
  cmd/platform/deployment-template/update.go
  cmd/platform/instance-configuration/create.go
  cmd/platform/instance-configuration/update.go
  cmd/platform/repository/create.go
Labels: Team:Delivery, bug

#338 mod: Update cobra, crypto and Go required verisons
  go.mod
  go.sum
Labels: Team:Delivery

#339 docs: Add all vacate kinds to `--kind` flag
  cmd/platform/allocator/vacate.go
  docs/ecctl_platform_allocator_vacate.adoc
  docs/ecctl_platform_allocator_vacate.md
  scripts/generate-docs.sh
Labels: Team:Delivery, documentation

#340 useragent: Add ecctl/<version> UserAgent header
  cmd/root.go
  cmd/root_test.go
  pkg/ecctl/app.go
Labels: Team:Delivery, enhancement

#342 enterprise_search: Support and refactor
  pkg/formatter/templates/bindata.go
  pkg/formatter/templates/text/deployment/list.gotmpl
  pkg/formatter/templates/text/deployment/search.gotmpl
  pkg/util/kinds.go
  pkg/util/testing.go
  pkg/util/track_test.go
  pkg/util/type.go
Labels: Team:Delivery, enhancement

#341 deployment: create flags reenabled and Enterprise Search support
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  cmd/deployment/create_test.go
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
  go.mod
  go.sum
Labels: Team:Delivery, enhancement

#346 allocator: Fix Array parsing to slice parsing
  cmd/platform/allocator/vacate.go
  docs/ecctl_platform_allocator_vacate.adoc
  docs/ecctl_platform_allocator_vacate.md
Labels: Team:Delivery, bug

#347 docs: Update to reflect the current state of the project
  developer_docs/NEW_COMMAND.md
  developer_docs/STYLEGUIDE.md
Labels: Team:Delivery, documentation

#348 deployment: Fix create command against ESS
  cmd/deployment/create.go
  cmd/deployment/create_test.go
  go.mod
  go.sum
Labels: Team:Delivery

#354 create: Use standard enterprise_search instead of enterprise-search
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  cmd/deployment/create_test.go
  cmd/deployment/show.go
  cmd/deployment/show_test.go
  cmd/deployment/testdata/show-resource.json
  cmd/deployment/testdata/show.json
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
Labels: breaking-change, bug

#356 deployment: Change of terminology for create command
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  cmd/deployment/create_test.go
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
  go.mod
  go.sum
Labels: breaking-change

#355 deployment: Add --generate-update-payload to show
  cmd/deployment/show.go
  cmd/deployment/show_test.go
  cmd/deployment/testdata/show_apm.json
  cmd/deployment/testdata/want_generate-payload.json
  cmd/deployment/update.go
  cmd/deployment/update_help.go
  docs/ecctl_deployment_show.adoc
  docs/ecctl_deployment_show.md
  docs/ecctl_deployment_update.adoc
  docs/ecctl_deployment_update.md
Labels: Team:Delivery, enhancement

#357 deployment: Support memory in GB for create command
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  cmd/deployment/create_test.go
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
Labels: breaking-change

#350 release: v1.0.0 release notes and changelog
  Makefile
  docs/ecctl-release-notes.asciidoc
  docs/release_notes/v1.0.0.adoc
  notes/v1.0.0.md
  scripts/changelog.tpl.adoc
Labels: Team:Delivery, documentation
