Repository elastic/ecctl, pull requests merged in 2020-08, with the labels that each got.

#361 cmd: Add region parameter to allocator metadata
  cmd/platform/allocator/metadata/command.go
Labels: bug

#360 cmd: Fix deployment note commands
  cmd/deployment/note/command.go
Labels: bug

#364 release: Update changelog prior to v1.0.0 release
  README.md
  docs/page_header.html
  docs/release_notes/v1.0.0.adoc
Labels: Team:Delivery, documentation

#365 docs: remove asciidoc beta disclaimer
  docs/ecctl-getting-started.asciidoc
Labels: documentation

#367 release: Fix changelog generator broken link
  scripts/changelog.tpl.md
  scripts/generate-changelog.sh
Labels: Team:Delivery, documentation

#368 version: Bump master branch to v1.1.0
  Makefile
Labels: Team:Delivery

#369 docs: Add asciidoc document validator in make docs
  scripts/generate-docs.sh
Labels: Team:Delivery, documentation

#366 release: Fix git commit by adding user and email
  scripts/update-brew-tap.sh
Labels: Team:Delivery

#372 deps: Enable renovate and update
  go.mod
  go.sum
  renovate.json
Labels: Team:Delivery
