Repository elastic/ecctl, pull requests merged in 2020-02, with the labels that each got.

#164 build: Add Go module cache for GitHub actions
  .github/workflows/go.yml
  .github/workflows/release.yml
Labels: area:tooling, enhancement, loe:small

#167 imports: update sdk to v1.0.0-beta1
  go.mod
  go.sum
Labels: area:tooling, loe:small

#176 allocator: Vacate now moves AppSearch instances
  pkg/platform/allocator/vacate.go
  pkg/platform/allocator/vacate_full_test.go
  pkg/platform/allocator/vacate_params.go
  pkg/platform/allocator/vacate_responses_test.go
  pkg/platform/allocator/vacate_test.go
Labels: area:tooling, bug, loe:medium

#177 makefile: update deps target to use cache
  build/Makefile.deps
  scripts/uname_arch.sh
Labels: area:tooling, loe:small

#173 cmd: init ask for type of infrastructure and default to ESS config setup
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: area:tooling, enhancement, loe:medium

#178 docs: update documentation and fix small grammar mistake
  docs/ecctl-getting-started.asciidoc
  pkg/ecctl/init.go
Labels: area:tooling, loe:small

#179 cmd: improve UX by defining which commands are only available in ECE
  cmd/util/help_text.go
  cmd/util/help_text_test.go
  docs/ecctl.md
  docs/ecctl_platform.md
  docs/ecctl_platform_allocator.md
  docs/ecctl_platform_allocator_list.md
  docs/ecctl_platform_allocator_maintenance.md
  docs/ecctl_platform_allocator_metadata.md
  docs/ecctl_platform_allocator_search.md
  docs/ecctl_platform_allocator_show.md
  docs/ecctl_platform_allocator_vacate.md
  docs/ecctl_platform_constructor.md
  docs/ecctl_platform_constructor_list.md
  docs/ecctl_platform_constructor_maintenance.md
  docs/ecctl_platform_constructor_resync.md
  docs/ecctl_platform_constructor_show.md
  docs/ecctl_platform_enrollment-token.md
  docs/ecctl_platform_enrollment-token_create.md
  docs/ecctl_platform_enrollment-token_delete.md
  docs/ecctl_platform_enrollment-token_list.md
  docs/ecctl_platform_info.md
  docs/ecctl_platform_instance-configuration.md
  docs/ecctl_platform_instance-configuration_create.md
  docs/ecctl_platform_instance-configuration_delete.md
  docs/ecctl_platform_instance-configuration_list.md
  docs/ecctl_platform_instance-configuration_pull.md
  docs/ecctl_platform_instance-configuration_show.md
  docs/ecctl_platform_instance-configuration_update.md
  docs/ecctl_platform_proxy.md
  docs/ecctl_platform_proxy_filtered-group.md
  docs/ecctl_platform_proxy_list.md
  docs/ecctl_platform_proxy_show.md
  docs/ecctl_platform_repository.md
  docs/ecctl_platform_repository_create.md
  docs/ecctl_platform_repository_delete.md
  docs/ecctl_platform_repository_list.md
  docs/ecctl_platform_repository_show.md
  docs/ecctl_platform_role.md
  docs/ecctl_platform_role_create.md
  docs/ecctl_platform_role_delete.md
  docs/ecctl_platform_role_list.md
  docs/ecctl_platform_role_show.md
  docs/ecctl_platform_runner.md
  docs/ecctl_platform_runner_list.md
  docs/ecctl_platform_runner_show.md
  docs/ecctl_platform_stack.md
  docs/ecctl_platform_stack_delete.md
  docs/ecctl_platform_stack_upload.md
  docs/ecctl_user.md
  docs/ecctl_user_create.md
  docs/ecctl_user_delete.md
  docs/ecctl_user_disable.md
  docs/ecctl_user_enable.md
  docs/ecctl_user_key.md
  docs/ecctl_user_list.md
  docs/ecctl_user_show.md
  docs/ecctl_user_update.md
Labels: area:tooling, loe:small

#184 cmd: mark --type flag as required for plan cancel
  cmd/deployment/plan/cancel.go
  docs/ecctl_deployment_plan_cancel.md
Labels: area:tooling, documentation, loe:small

#187 cmd: new appsearch create --id <deployment id>
  cmd/deployment/appsearch/command.go
  cmd/deployment/appsearch/create.go
  cmd/deployment/appsearch/create_help.go
  cmd/deployment/appsearch/show.go
  docs/ecctl_deployment_appsearch.md
  docs/ecctl_deployment_appsearch_create.md
  pkg/deployment/depresource/appsearch.go
  pkg/deployment/depresource/appsearch_test.go
Labels: area:tooling, enhancement, loe:medium

#185 Remove extra v in help file
  scripts/Makefile.help
Labels: area:tooling

#180 cmd: init gives you a choice to select default region when ESS is selected
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: ESS, area:tooling, enhancement, loe:small

#189 cmd: init now only allows API key auth for ESS users
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: area:tooling, enhancement

#190 docs: change to specify that ecctl is no longer ECE specific
  README.md
  docs/ecctl-getting-started.asciidoc
Labels: ESS, area:tooling, loe:small

#197 init: Provide alternative API validation call
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: area:tooling, bug, loe:small

#195 Add release notes stub for 1.0.0-beta2
  docs/ecctl-release-notes.asciidoc
Labels: documentation

#198 deployment: Add --plan-history flag to show cmd
  cmd/deployment/show.go
  docs/ecctl_deployment_show.md
  pkg/deployment/deputil/deputil.go
  pkg/deployment/get.go
Labels: area:tooling, loe:small

#199 release: Change GitHub token for Tap modifications
  .github/workflows/release.yml
Labels: area:tooling, loe:small
