Repository elastic/ecctl, pull requests merged in 2020-03, with the labels that each got.

#201 vendor: Update elastic/cloud-sdk-go to 8877c73
  go.mod
  go.sum
Labels: area:tooling, bug, loe:small

#202 deps: Bump golangci-lint to v1.23.8
  .golangci.yml
  build/Makefile.deps
Labels: area:tooling, loe:small

#205 cmd: Handle case when deployment template does not include resource
  pkg/deployment/depresource/apm.go
  pkg/deployment/depresource/apm_test.go
  pkg/deployment/depresource/appsearch.go
  pkg/deployment/depresource/appsearch_test.go
Labels: area:tooling, bug, loe:medium

#206 cmd: Handle case when deployment template does not include kibana
  pkg/deployment/depresource/kibana.go
  pkg/deployment/depresource/kibana_test.go
Labels: area:tooling, loe:small

#207 init: Revert to ECE only workflow with bool toggle
  cmd/init.go
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: area:tooling, loe:small

#208 misc: Replace all references from cluster type to resource kind
  cmd/deployment/appsearch/delete.go
  cmd/deployment/appsearch/show.go
  cmd/deployment/appsearch/shutdown.go
  cmd/deployment/appsearch/upgrade.go
  cmd/deployment/plan/cancel.go
  cmd/deployment/resource/delete.go
  cmd/deployment/resource/restore.go
  cmd/deployment/resource/shutdown.go
  cmd/deployment/resource/shutdown_help.go
  cmd/deployment/resource/start-maintenance.go
  cmd/deployment/resource/start.go
  cmd/deployment/resource/stop-maintenance.go
  cmd/deployment/resource/stop.go
  cmd/deployment/resource/upgrade.go
  cmd/deployment/resource/upgrade_help.go
  cmd/deployment/show.go
  cmd/root.go
  cmd/util/flag.go
  cmd/util/flag_test.go
  docs/ecctl_deployment_plan_cancel.md
  docs/ecctl_deployment_resource.md
  docs/ecctl_deployment_resource_delete.md
  docs/ecctl_deployment_resource_restore.md
  docs/ecctl_deployment_resource_shutdown.md
  docs/ecctl_deployment_resource_start-maintenance.md
  docs/ecctl_deployment_resource_start.md
  docs/ecctl_deployment_resource_stop-maintenance.md
  docs/ecctl_deployment_resource_stop.md
  docs/ecctl_deployment_resource_upgrade.md
  docs/ecctl_deployment_show.md
  pkg/deployment/depresource/cancel_plan.go
  pkg/deployment/depresource/cancel_plan_test.go
  pkg/deployment/depresource/delete_stateless.go
  pkg/deployment/depresource/delete_stateless_test.go
  pkg/deployment/depresource/restore.go
  pkg/deployment/depresource/restore_test.go
  pkg/deployment/depresource/shutdown.go
  pkg/deployment/depresource/shutdown_test.go
  pkg/deployment/depresource/start.go
  pkg/deployment/depresource/start_maintenance.go
  pkg/deployment/depresource/start_maintenance_test.go
  pkg/deployment/depresource/start_test.go
  pkg/deployment/depresource/stop.go
  pkg/deployment/depresource/stop_maintenance.go
  pkg/deployment/depresource/stop_maintenance_test.go
  pkg/deployment/depresource/stop_test.go
  pkg/deployment/depresource/track_test.go
  pkg/deployment/depresource/upgrade_stateless.go
  pkg/deployment/depresource/upgrade_stateless_test.go
  pkg/deployment/deputil/deputil_test.go
  pkg/deployment/get_resource.go
  pkg/deployment/get_resource_test.go
  pkg/deployment/note/params.go
  pkg/deployment/params.go
  pkg/deployment/params_test.go
  pkg/deployment/shutdown.go
Labels: area:tooling, breaking-change, loe:medium

#209 docs: Ammend Readme.md to clarify ECE only for now
  README.md
Labels: area:tooling, documentation, loe:small

#210 github actions: Update checkout action to v2
  .github/workflows/go.yml
  .github/workflows/release.yml
Labels: area:tooling, bug, loe:small

#211 vendor: Update cloud-sdk-go to v1.0.0-beta2
  cmd/deployment/elasticsearch/start.go
  cmd/deployment/kibana/show_test.go
  cmd/deployment/kibana/start.go
  cmd/util/testutils/testutils.go
  go.mod
  go.sum
  pkg/deployment/apm/delete.go
  pkg/deployment/apm/delete_test.go
  pkg/deployment/apm/plan_test.go
  pkg/deployment/apm/read_test.go
  pkg/deployment/create_test.go
  pkg/deployment/depresource/apm_test.go
  pkg/deployment/depresource/appsearch_test.go
  pkg/deployment/depresource/cancel_plan_test.go
  pkg/deployment/depresource/kibana_test.go
  pkg/deployment/depresource/start_maintenance_test.go
  pkg/deployment/depresource/start_test.go
  pkg/deployment/depresource/stop_test.go
  pkg/deployment/elasticsearch/delete.go
  pkg/deployment/elasticsearch/delete_test.go
  pkg/deployment/elasticsearch/instances/override.go
  pkg/deployment/elasticsearch/instances/override_test.go
  pkg/deployment/get_resource_test.go
  pkg/deployment/get_test.go
  pkg/deployment/kibana/delete.go
  pkg/deployment/kibana/delete_test.go
  pkg/deployment/kibana/read_test.go
  pkg/deployment/note/list.go
  pkg/deployment/note/show.go
  pkg/deployment/note/update.go
  pkg/deployment/note/write.go
  pkg/ecctl/config.go
  pkg/platform/allocator/vacate_test.go
  pkg/platform/constructor/constructor_test.go
  pkg/platform/deployment/template_test.go
Labels: area:tooling, loe:small

#212 release: Add v1.0.0-beta2 release notes
  Makefile
  build/Makefile.build
  docs/ecctl-release-notes.asciidoc
  docs/release_notes/v1.0.0-beta1.adoc
  docs/release_notes/v1.0.0-beta2.adoc
  notes/v1.0.0-beta2.md
Labels: area:tooling, documentation, loe:medium

#215 Fix small formatting mistake on Release Notes
  docs/release_notes/v1.0.0-beta2.adoc
Labels: area:tooling, bug, documentation

#214 Fix GitHub release action
  scripts/goreleaser-post-actions.sh
  scripts/update-brew-tap.sh
Labels: area:tooling, bug, loe:small

#217 docs: Modify changelog generator for adoc files
  scripts/changelog.tpl.adoc
  scripts/changelog.tpl.md
  scripts/generate-changelog.sh
Labels: area:tooling, documentation, enhancement, loe:small

#218 init: Change example command to deployment list
  pkg/ecctl/init.go
Labels: area:tooling, bug, loe:small

#219 docs: Add brew upgrade instructions
  docs/ecctl-getting-started.asciidoc
Labels: area:tooling, documentation, loe:small

#227 misc: change codeowners
  .github/CODEOWNERS
Labels: area:delivery, loe:small

#224 cmd: add instance flags to deployment create command
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_create.md
  pkg/deployment/depresource/apm_test.go
  pkg/deployment/depresource/appsearch_test.go
  pkg/deployment/depresource/kibana_test.go
  pkg/deployment/depresource/new_deployment.go
  pkg/deployment/depresource/new_deployment_test.go
  pkg/deployment/depresource/new_stateless.go
Labels: area:delivery, breaking-change, enhancement

#232 cmd: specify that deployment template commands are ECE specific
  cmd/platform/deployment-template/command.go
  docs/ecctl_platform.md
  docs/ecctl_platform_deployment-template.md
  docs/ecctl_platform_deployment-template_create.md
  docs/ecctl_platform_deployment-template_delete.md
  docs/ecctl_platform_deployment-template_list.md
  docs/ecctl_platform_deployment-template_pull.md
  docs/ecctl_platform_deployment-template_show.md
  docs/ecctl_platform_deployment-template_update.md
Labels: area:delivery, bug, loe:small

#233 cmd: specify that deployment delete command is ECE specific
  cmd/deployment/delete.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_delete.md
Labels: ESS, area:delivery, bug, loe:small
