Repository elastic/ecctl, pull requests merged in 2020-06, with the labels that each got.

#300 docs: Add --track flag to the deployment examples
  docs/ecctl-getting-started.asciidoc
Labels: documentation

#301 docs: Add --track flag to the deployment examples
  docs/ecctl-getting-started.asciidoc
Labels: documentation

#303 stack: Populate stackapi Region field
  cmd/platform/stack/command.go
  go.mod
  go.sum
Labels: Team:Delivery

#311 misc: Removes files related to clusters API
  pkg/util/response_parse.go
  pkg/util/response_parse_test.go
Labels: Team:Delivery

#308 runner: Populate Region field API calls
  cmd/platform/runner/list.go
  cmd/platform/runner/resync.go
  cmd/platform/runner/search.go
  cmd/platform/runner/show.go
  go.mod
  go.sum
Labels: Team:Delivery

#309 role: Populate Region field API calls
  cmd/platform/role/create.go
  cmd/platform/role/delete.go
  cmd/platform/role/list.go
  cmd/platform/role/show.go
  go.mod
  go.sum
Labels: Team:Delivery

#316 deployment-template: Update commands with region
  cmd/platform/deployment-template/command.go
  cmd/platform/deployment-template/create.go
  cmd/platform/deployment-template/delete.go
  cmd/platform/deployment-template/list.go
  cmd/platform/deployment-template/pull.go
  cmd/platform/deployment-template/show.go
  cmd/platform/deployment-template/update.go
  go.mod
  go.sum
Labels: Team:Delivery

#320 platform: Update info command with region
  cmd/platform/command.go
  cmd/platform/info.go
  go.mod
  go.sum
Labels: Team:Delivery

#328 user: remove user api and update with sdk imports
  cmd/auth/key/create.go
  cmd/auth/key/delete.go
  cmd/auth/key/list.go
  cmd/auth/key/show.go
  cmd/user/create.go
  cmd/user/delete.go
  cmd/user/disable.go
  cmd/user/enable.go
  cmd/user/key/delete.go
  cmd/user/key/list.go
  cmd/user/key/show.go
  cmd/user/list.go
  cmd/user/show.go
  cmd/user/update.go
  pkg/ecctl/init.go
  pkg/user/auth/admin/deletekey.go
  pkg/user/auth/admin/deletekey_test.go
  pkg/user/auth/admin/doc.go
  pkg/user/auth/admin/getkey.go
  pkg/user/auth/admin/getkey_test.go
  pkg/user/auth/admin/listkeys.go
  pkg/user/auth/admin/listkeys_test.go
  pkg/user/auth/createkey.go
  pkg/user/auth/createkey_test.go
  pkg/user/auth/deletekey.go
  pkg/user/auth/deletekey_test.go
  pkg/user/auth/doc.go
  pkg/user/auth/getkey.go
  pkg/user/auth/getkey_test.go
  pkg/user/auth/listkeys.go
  pkg/user/auth/listkeys_test.go
  pkg/user/auth/reauthenticate.go
  pkg/user/create.go
  pkg/user/create_test.go
  pkg/user/delete.go
  pkg/user/delete_test.go
  pkg/user/doc.go
  pkg/user/enable.go
  pkg/user/enable_test.go
  pkg/user/get.go
  pkg/user/get_test.go
  pkg/user/list.go
  pkg/user/list_test.go
  pkg/user/roles.go
  pkg/user/roles_test.go
  pkg/user/update.go
  pkg/user/update_test.go
  pkg/util/email.go
  pkg/util/email_test.go
Labels: Team:Delivery, breaking-change

#330 cmd/util/testutils: Add RunCmdAssertion test function
  cmd/deployment/create.go
  cmd/deployment/create_test.go
  cmd/deployment/testdata/create-aws.json
  cmd/deployment/testdata/create-azure.json
  cmd/util/testutils/cmd.go
  cmd/util/testutils/testutils.go
  cmd/util/testutils/testutils_test.go
  cmd/util/track_params.go
  go.mod
Labels: Team:Delivery
