Repository elastic/ecctl, pull requests merged in 2020-04, with the labels that each got.

#239 cmd: Temporarily remove ability to create a flag based deployment
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  docs/ecctl_deployment_create.md
Labels: ESS, area:delivery, breaking-change, loe:small

#240 deps: revert multierror to 1.0.0
  go.mod
  go.sum
Labels: area:delivery, loe:small

#242 cmd: Add missing NewTrackParams tests
  cmd/util/track_params_test.go
Labels: area:delivery, loe:small

#241 Remove "deployment apm" command and subcommands
  cmd/deployment/apm/command.go
  cmd/deployment/apm/create.go
  cmd/deployment/apm/create_help.go
  cmd/deployment/apm/delete.go
  cmd/deployment/apm/list.go
  cmd/deployment/apm/plan/cancel.go
  cmd/deployment/apm/plan/command.go
  cmd/deployment/apm/plan/history.go
  cmd/deployment/apm/plan/monitor.go
  cmd/deployment/apm/plan/reapply.go
  cmd/deployment/apm/restart.go
  cmd/deployment/apm/resync.go
  cmd/deployment/apm/show.go
  cmd/deployment/apm/stop.go
  cmd/deployment/apm/upgrade.go
  cmd/deployment/command.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_apm.adoc
  docs/ecctl_deployment_apm.md
  docs/ecctl_deployment_apm_create.adoc
  docs/ecctl_deployment_apm_create.md
  docs/ecctl_deployment_apm_delete.adoc
  docs/ecctl_deployment_apm_delete.md
  docs/ecctl_deployment_apm_list.adoc
  docs/ecctl_deployment_apm_list.md
  docs/ecctl_deployment_apm_plan.adoc
  docs/ecctl_deployment_apm_plan.md
  docs/ecctl_deployment_apm_plan_cancel.adoc
  docs/ecctl_deployment_apm_plan_cancel.md
  docs/ecctl_deployment_apm_plan_history.adoc
  docs/ecctl_deployment_apm_plan_history.md
  docs/ecctl_deployment_apm_plan_monitor.adoc
  docs/ecctl_deployment_apm_plan_monitor.md
  docs/ecctl_deployment_apm_plan_reapply.adoc
  docs/ecctl_deployment_apm_plan_reapply.md
  docs/ecctl_deployment_apm_restart.adoc
  docs/ecctl_deployment_apm_restart.md
  docs/ecctl_deployment_apm_resync.adoc
  docs/ecctl_deployment_apm_resync.md
  docs/ecctl_deployment_apm_show.adoc
  docs/ecctl_deployment_apm_show.md
  docs/ecctl_deployment_apm_stop.adoc
  docs/ecctl_deployment_apm_stop.md
  docs/ecctl_deployment_apm_upgrade.adoc
  docs/ecctl_deployment_apm_upgrade.md
  pkg/deployment/apm/delete.go
  pkg/deployment/apm/delete_test.go
  pkg/deployment/apm/plan.go
  pkg/deployment/apm/plan_test.go
  pkg/deployment/apm/read.go
  pkg/deployment/apm/read_test.go
  pkg/deployment/apm/restart.go
  pkg/deployment/apm/restart_test.go
  pkg/deployment/apm/resync.go
  pkg/deployment/apm/resync_test.go
  pkg/deployment/apm/upgrade.go
  pkg/deployment/apm/upgrade_test.go
Labels: area:delivery, breaking-change

#243 cmd: Remove deployment appsearch specific commands
  cmd/deployment/appsearch/command.go
  cmd/deployment/appsearch/create.go
  cmd/deployment/appsearch/create_help.go
  cmd/deployment/appsearch/delete.go
  cmd/deployment/appsearch/show.go
  cmd/deployment/appsearch/shutdown.go
  cmd/deployment/appsearch/upgrade.go
  cmd/deployment/command.go
  docs/ecctl_deployment.md
  docs/ecctl_deployment_appsearch.md
  docs/ecctl_deployment_appsearch_create.md
  docs/ecctl_deployment_appsearch_delete.md
  docs/ecctl_deployment_appsearch_show.md
  docs/ecctl_deployment_appsearch_shutdown.md
  docs/ecctl_deployment_appsearch_upgrade.md
Labels: area:delivery, breaking-change, loe:small

#249 docs: Adds Asciidoc generation to "make docs"
  build/Makefile.dev
  cmd/deployment/create_help.go
  docs/ecctl_deployment_create.md
  scripts/generate-docs.sh
Labels: area:delivery, documentation, loe:small

#250 formatter: Remove apm and kibana text templates
  pkg/formatter/templates/bindata.go
  pkg/formatter/templates/text/apm/list.gotmpl
  pkg/formatter/templates/text/apm/planhistory.gotmpl
  pkg/formatter/templates/text/kibana/enable.gotmpl
  pkg/formatter/templates/text/kibana/list.gotmpl
Labels: area:delivery, loe:small

#255 docs: update getting-started ascii doc
  docs/ecctl-getting-started.asciidoc
Labels: area:delivery, documentation, loe:small

#254 ecctl: Prefix config parsing error
  NOTICE
  cmd/root.go
  cmd/root_test.go
  go.mod
  go.sum
  pkg/ecctl/config.go
  pkg/ecctl/config_test.go
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
  pkg/ecctl/singleton.go
Labels: area:delivery, bug, loe:small

#258 api: Remove code that is related to clusters API
  cmd/util/flag.go
  cmd/util/flag_test.go
  pkg/deployment/elasticsearch/get.go
  pkg/deployment/elasticsearch/get_test.go
  pkg/deployment/elasticsearch/instances/reducer.go
  pkg/deployment/elasticsearch/instances/reducer_test.go
  pkg/util/helper.go
  pkg/util/helper_test.go
Labels: area:delivery, loe:small

#259 Fix some typos
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  pkg/deployment/depresource/appsearch.go
  pkg/deployment/depresource/appsearch_test.go
  pkg/deployment/depresource/delete_stateless.go
  pkg/deployment/depresource/new_deployment_test.go
  pkg/deployment/depresource/restore.go
  pkg/deployment/depresource/upgrade_stateless.go
  pkg/platform/allocator/vacate_responses_test.go
  pkg/platform/allocator/vacate_test.go
Labels: area:delivery, loe:small

#263 docs: Add Nik and Arianna as CODEOWNERS
  .github/CODEOWNERS
Labels: area:delivery, documentation, loe:small

#264 Remove reference to Ansible and Terraform
  docs/ecctl-getting-started.asciidoc
Labels: documentation

#266 misc: Add delivery team as docs codeowner
  .github/CODEOWNERS
Labels: area:delivery

#265 Remove reference to Ansible and Terraform - cherry pick
  docs/ecctl-getting-started.asciidoc
Labels: documentation

#269 deps: Update SDK dependency to v1.0.0-beta3
  go.mod
  go.sum
Labels: area:delivery, dependencies

#270 cmd: Change --cluster flag to --resource-id
  cmd/platform/allocator/vacate.go
  cmd/platform/allocator/vacate_test.go
  docs/ecctl_platform_allocator.adoc
  docs/ecctl_platform_allocator.md
  docs/ecctl_platform_allocator_vacate.adoc
  docs/ecctl_platform_allocator_vacate.md
Labels: area:delivery, breaking-change

#268 cmd: Show ESS options in init command flow
  cmd/init.go
  pkg/ecctl/init.go
  pkg/ecctl/init_test.go
Labels: ESS, area:delivery

#267 docs: add references to Elasticsearch Service
  README.md
  docs/ecctl-getting-started.asciidoc
  scripts/changelog.tpl.adoc
Labels: ESS, area:delivery, blocked
