Repository elastic/ecctl, pull requests merged in 2021-03, with the labels that each got.

#453 mod: Update cloud-sdk-go to post swagger update
  cmd/deployment/create_test.go
  cmd/deployment/elasticsearch/keystore/show_test.go
  cmd/deployment/elasticsearch/keystore/update_test.go
  cmd/deployment/show_test.go
  go.mod
  go.sum
Labels: dependencies

#454 mod: Update sdk to fix plan tracker bugs
  go.mod
  go.sum
Labels: Team:Delivery, dependencies

#457 gh issues: Update bug issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: documentation

#458 deployment: Adds read and delete extension subcommands
  cmd/deployment/command.go
  cmd/deployment/extension/command.go
  cmd/deployment/extension/delete.go
  cmd/deployment/extension/delete_test.go
  cmd/deployment/extension/list.go
  cmd/deployment/extension/list_test.go
  cmd/deployment/extension/show.go
  cmd/deployment/extension/show_test.go
  cmd/deployment/extension/testdata/list.json
  cmd/deployment/extension/testdata/show-dep.json
  cmd/deployment/extension/testdata/show.json
  docs/ecctl-command-reference-index.adoc
  docs/ecctl_deployment.adoc
  docs/ecctl_deployment.md
  docs/ecctl_deployment_extension.adoc
  docs/ecctl_deployment_extension.md
  docs/ecctl_deployment_extension_delete.adoc
  docs/ecctl_deployment_extension_delete.md
  docs/ecctl_deployment_extension_list.adoc
  docs/ecctl_deployment_extension_list.md
  docs/ecctl_deployment_extension_show.adoc
  docs/ecctl_deployment_extension_show.md
Labels: enhancement

#462 comment: Adjust text to specify the command is ECE only
  cmd/comment/command.go
  cmd/comment/create.go
  cmd/comment/update.go
  docs/ecctl.adoc
  docs/ecctl.md
  docs/ecctl_comment.adoc
  docs/ecctl_comment.md
  docs/ecctl_comment_create.adoc
  docs/ecctl_comment_create.md
  docs/ecctl_comment_delete.adoc
  docs/ecctl_comment_delete.md
  docs/ecctl_comment_list.adoc
  docs/ecctl_comment_list.md
  docs/ecctl_comment_show.adoc
  docs/ecctl_comment_show.md
  docs/ecctl_comment_update.adoc
  docs/ecctl_comment_update.md
Labels: documentation

#460 deployment command: Remove flag based create
  cmd/deployment/create.go
  cmd/deployment/create_help.go
  cmd/deployment/create_test.go
  cmd/deployment/testdata/template-aws-io-optimized-v2.json
  docs/ecctl_deployment_create.adoc
  docs/ecctl_deployment_create.md
  go.mod
  go.sum
Labels: Team:Delivery, breaking-change

#469 traffic-filter: Fix deleteCmd test
  cmd/deployment/trafficfilter/delete_test.go
Labels: bug

#473 Bump to cloud-sdk-go v1.3.0
  go.mod
  go.sum
Labels: dependencies

#474 release: Generate changelog, set version to 1.3.0
  Makefile
  docs/ecctl-release-notes.asciidoc
  docs/release_notes/v1.3.0.adoc
  notes/v1.3.0.md
Labels: documentation

#478 release: latest round of goreleaser patches
  .github/workflows/release.yml
  scripts/update-brew-tap.sh
Labels: Team:Delivery
