Repository elastic/ecctl, pull requests merged in 2021-02, with the labels that each got.

#438 deps: Update to cloud-sdk-go v1.2.0
  go.mod
  go.sum
  pkg/ecctl/app_test.go
Labels: dependencies

#439 release: Release notes and changelog for v1.2.0
  Makefile
  docs/ecctl-release-notes.asciidoc
  docs/release_notes/v1.2.0.adoc
  notes/v1.2.0.md
Labels: documentation

#440 docs: Improved release documentation
  .github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md
  developer_docs/RELEASE.md
Labels: documentation

#442 fixup: release notes
  docs/release_notes/v1.2.0.adoc
Labels: bug, documentation

#443 build: Fix release GH action
  .github/workflows/release.yml
Labels: bug

#446 docs: Set deployment node command as ECE only
  cmd/deployment/note/command.go
  docs/ecctl_deployment.adoc
  docs/ecctl_deployment.md
  docs/ecctl_deployment_note.adoc
  docs/ecctl_deployment_note.md
  docs/ecctl_deployment_note_create.adoc
  docs/ecctl_deployment_note_create.md
  docs/ecctl_deployment_note_list.adoc
  docs/ecctl_deployment_note_list.md
  docs/ecctl_deployment_note_show.adoc
  docs/ecctl_deployment_note_show.md
  docs/ecctl_deployment_note_update.adoc
  docs/ecctl_deployment_note_update.md
Labels: documentation

#447 backport: Set deployment node command docs as ECE only
  cmd/deployment/note/command.go
  docs/ecctl_deployment.adoc
  docs/ecctl_deployment.md
  docs/ecctl_deployment_note.adoc
  docs/ecctl_deployment_note.md
  docs/ecctl_deployment_note_create.adoc
  docs/ecctl_deployment_note_create.md
  docs/ecctl_deployment_note_list.adoc
  docs/ecctl_deployment_note_list.md
  docs/ecctl_deployment_note_show.adoc
  docs/ecctl_deployment_note_show.md
  docs/ecctl_deployment_note_update.adoc
  docs/ecctl_deployment_note_update.md
Labels: documentation

#450 mod: Updates SDK to ECE 2.9.0 spec
  cmd/deployment/create_test.go
  cmd/deployment/testdata/want_generate-payload.json
  cmd/init.go
  go.mod
  go.sum
  pkg/ecctl/read_secret.go
Labels: Team:Delivery, dependencies
